### ISSUE TITLE
Multi msg debug module call should print messages verbatimly when `debug` stdout_callback plugin is used

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [ansible-collections/ansible.posix#16] opened 2020-04-24 16:54 UTC
##### SUMMARY
When `debug` stdout_callback plugin is used, multi messages from a single `debug` module call is printed as a Python sequence representation instead of printing them verbatimly, preventing user from reading it easily, refer the issue production for an example.

As a side issue non-ASCII characters are printed as Unicode escapes in this case, though this problem is only reproduced when the controller node's Python interpreter is in version 2.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
debug

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /vagrant/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
DEFAULT_STDOUT_CALLBACK(/home/vagrant/ansible.cfg) = debug
```

##### OS / ENVIRONMENT
Controller: CentOS 7
Managed node: CentOS 7

##### STEPS TO REPRODUCE

1. Create ansible.cfg with the following content:
    ```ini
    [defaults]
    stdout_callback = debug
    ```
1. Run the following playbook
    
    ```yaml
    - name: Test Ansible issue
      gather_facts: False
      hosts: localhost
      tasks:
        - name: Print single message
          debug:
            msg: 'Welcome to the world of Ansible / 歡迎來到Ansible的世界 / Ansibleの世界へようこそ'

        - name: Print multiple messages at once
          debug:
            msg:
              - 'Welcome to the world of Ansible'
              - '歡迎來到Ansible的世界'
              - 'Ansibleの世界へようこそ'
    ```

##### EXPECTED RESULTS
In the `Print multiple messages at once` task the messages should be printed in plain order.

```
TASK [Print single message] ******************************************************************************************
ok: [localhost] => {}

MSG:

Welcome to the world of Ansible / 歡迎來到Ansible的世界 / Ansibleの世界へようこそ

TASK [Print multiple messages at once] *******************************************************************************
ok: [localhost] => {}

MSG:

Welcome to the world of Ansible
歡迎來到Ansible的世界
Ansibleの世界へようこそ
```

##### ACTUAL RESULTS
In the `Print multiple messages at once` task the messages are printed as a Python sequence markup.  Also if the controller's Python interpreter is 2 non-ASCII characters are printed as Unicode escape sequences.

```paste below
TASK [Print single message] ******************************************************************************************
ok: [localhost] => {}

MSG:

Welcome to the world of Ansible / 歡迎來到Ansible的世界 / Ansibleの世界へようこそ

TASK [Print multiple messages at once] *******************************************************************************
ok: [localhost] => {}

MSG:

[u'Welcome to the world of Ansible', u'\u6b61\u8fce\u4f86\u5230Ansible\u7684\u4e16\u754c', u'Ansible\u306e\u4e16\u754c\u3078\u3088\u3046\u3053\u305d']
```

**Comment by marcinkubica** [comment] 2020-05-14 13:39
Yes please!!

**Comment by maxamillion** [comment] 2020-09-28 17:28
This appears to be functioning as designed and as intended. A YAML list should be displayed as separate disjoint entities because that's exactly what is being passed in to the playbook for debug and therefore that's the data type that should be displayed. If the desired outcome is to have a multi-line string then use a [YAML multi-line string data type](https://yaml-multiline.info/).

**Comment by Akasurde** [comment] 2021-06-21 11:35
I am unable to reproduce this.

```
MSG:

['Welcome to the world of Ansible', '歡迎來到Ansible的世界', 'Ansibleの世界へようこそ']
```

Closing this as per the above comment.

**Closed by Akasurde** 2021-06-21 11:35 UTC
Labels: needs_info
