### ISSUE TITLE
synchronize module fails during molecule test with "rsync: Failed to exec /usr/bin/docker: No such file or directory"

### ISSUE THREAD

**Issue by guerzon** [ansible-collections/ansible.posix#51] opened 2020-06-18 12:47 UTC
##### SUMMARY

This is regarding the error in the title of this report when running `molecule tests` using `docker` and the `synchronize` module. Here is my setup:
* ansible controller: `macbookC`
* ansible host: server `serverB`
* remote user: `root`
* there is another server, `serverA` (details below).
* both servers are `Docker` containers (image: `geerlingguy/docker-centos7-ansible`).

Goal: Using molecule to test the task to synchronize all the files in `serverA:/opt/appowner/appdir/app/` to `serverB:/opt/appowner/appdir/app/`.

Ownership: All these files and directories are owned by the application user called `appowner`.

Here is the task in question:

```
- name: Synchronize configs from serverA to serverB
  become: true
  become_user: appowner
  synchronize:
    src: "/opt/appowner/appdir/app/"
    dest: "/opt/appowner/appdir/app/"
    set_remote_user: false
    rsync_path: "/bin/rsync"
    rsync_opts:
      - "--prune-empty-dirs"
  delegate_to: "serverA"
  when: inventory_hostname == "serverB"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`synchronize` module

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = /Users/myuser/PROJECTS/ansibledevel/ansible.cfg
  configured module search path = ['/Users/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Dec 13 2019, 19:58:14) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/Users/myuser/PROJECTS/ansibledevel/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/Users/myuser/PROJECTS/ansibledevel/ansible.cfg) = ['profile_tasks']
DEFAULT_INVENTORY_PLUGIN_PATH(/Users/myuser/PROJECTS/ansibledevel/ansible.cfg) = ['/Users/myuser/PROJECTS/ansibledevel/additional_plugins/inventory']
DEFAULT_LOOKUP_PLUGIN_PATH(/Users/myuser/PROJECTS/ansibledevel/ansible.cfg) = ['/Users/myuser/PROJECTS/ansibledevel/additional_plugins/lookup']
DEFAULT_ROLES_PATH(/Users/myuser/PROJECTS/ansibledevel/ansible.cfg) = ['/Users/myuser/PROJECTS/ansibledevel/roles', '/etc/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/Users/myuser/PROJECTS/ansibledevel/ansible.cfg) = skippy
INVENTORY_ENABLED(/Users/myuser/PROJECTS/ansibledevel/ansible.cfg) = ['host_list', 'script', 'yaml', 'auto', 'ini', 'tpm_inventory']
```

##### OS / ENVIRONMENT

Ansible controller: macOS Catalina, Docker version 19.03.8, build afacb8b
Ansible hosts `serverA` and `serverB`: containers using `geerlingguy/docker-centos7-ansible`.

##### STEPS TO REPRODUCE

1. Create a simple molecule test using `docker` and a CentOS 7 image (ex. `geerlingguy/docker-centos7-ansible`).
2. Define 2 servers in the molecule test, serverB and serverA.
3. In the molecule test, create the user `appowner`.
4. In the molecule test, configure passwordless SSH for appowner on serverA to serverB.
5. Also create the directory structure `/opt/appowner/appdir/app/` on both containers.
6. Run the molecule test with the task in the summary section.

```yaml
molecule test
```

##### EXPECTED RESULTS

The task should successfully synchronize the directory from serverA to serverB.

##### ACTUAL RESULTS

The task fails with: `rsync: Failed to exec /usr/bin/docker: No such file or directory`.

```paste below
    TASK [app-setup : Synchronize configs from serverA to serverB] ***************
    fatal: [serverB -> serverA]: FAILED! => {"changed": false, "cmd": "/bin/rsync --delay-updates -F --compress --archive --rsync-path=/bin/rsync --prune-empty-dirs --blocking-io --rsh=/usr/local/bin/docker exec -u appowner -i --out-format=<<CHANGED>>%i %n%L /opt/appowner/appdir/app/ serverB:/opt/appowner/appdir/app/", "msg": "rsync: Failed to exec /usr/local/bin/docker: No such file or directory (2)\nrsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.1.2]\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: error in IPC code (code 14) at io.c(226) [sender=3.1.2]\n", "rc": 14}
```

##### Important Notes
* The `macOS` ansible controller is also the Docker host since it is running the molecule tests.
* On the `macOS` ansible controller, `/usr/local/bin/docker` exists:
`lrwxr-xr-x  1 myuser  admin  54 Jan 28 11:30 /usr/local/bin/docker -> /Applications/Docker.app/Contents/Resources/bin/docker`

##### Interesting observations
* The task only fails during molecule testing on a `macOS` machine.
* When testing on a `CentOS` build server, the task completes successfully.
* When the play executed against actual servers using `ansible-playbook` command, the task completes successfully.
* When the play executed against actual servers using Ansible Tower (AWX), the task completes successfully.

Thanks in advance for any help.

Cheers.

**Comment by maxamillion** [comment] 2020-06-19 04:24
@guerzon is this using the `docker` connection plugin? I'm curious if this is actually either a molecule or docker connection plugin issue since the module works on CentOS as you noted and the error looks as though the failure is from the `--rsh` option to `rsync` which would have to be set by the `rsync_opts` because if that value is the empty string then it defaults to `ssh`. This leads me to believe that either the `docker` connection plugin is overriding something or molecule is.

**Comment by saito-hideki** [comment] 2021-12-05 02:19
@guerzon This issue has not been updated in 1+ years. Therefore, I will close this issue. If you are still running into this issue after you confirmed connection plugin settings according to the advice from @maxamillion, you can feel free to reopen this.

**Closed by saito-hideki** 2021-12-05 02:19 UTC
Labels: bug, needs_info
