### ISSUE TITLE
The json callback plugin return multiple json results when multiple playbooks are executed

### ISSUE THREAD

**Issue by lucas-benedito** [ansible-collections/ansible.posix#105] opened 2020-10-27 12:16 UTC
##### SUMMARY
The json callback plugin return multiple json results when multiple playbooks are executed.
This issue has been pointed out previously in the issue [#38804](https://github.com/ansible/ansible/issues/38804)

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/lbenedit/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.6 (default, Sep 25 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
```

##### CONFIGURATION
```
ANSIBLE_STDOUT_CALLBACK=json
```

##### STEPS TO REPRODUCE
Create 2 playbooks:

play1.yml:
```
---
- hosts: all
  gather_facts: false
  tasks: 
    - name: Play 1
      debug: msg="This is play 1"
```
play2.yml:
```
---
- hosts: all
  gather_facts: false
  tasks: 
    - name: Play 2
      debug: msg="This is play 2"
```

And execute them using the json callback plugin:

$ ANSIBLE_STDOUT_CALLBACK=json ansible-playbook -i localhost, play1.yml play2.yml

##### EXPECTED RESULTS
A valid json structure
```
# ANSIBLE_STDOUT_CALLBACK=json ansible-playbook -i localhost, play1.yml play2.yml | json_verify 
JSON is valid
#
```

##### ACTUAL RESULTS
```
# ANSIBLE_STDOUT_CALLBACK=json ansible-playbook -i localhost, play1.yml play2.yml | json_verify 
parse error: trailing garbage
                                        {     "custom_stats": {},     
                     (right here) ------^
JSON is invalid
#
```
```
{
    "custom_stats": {},
    "global_custom_stats": {},
    "plays": [
        {
            "play": {
                "duration": {
                    "end": "2020-10-27T12:12:51.186216Z",
                    "start": "2020-10-27T12:12:51.172245Z"
                },
                "id": "58961d97-78ae-5e1e-8808-000000000006",
                "name": "all"
            },
            "tasks": [
                {
                    "hosts": {
                        "localhost": {
                            "_ansible_no_log": false,
                            "_ansible_verbose_always": true,
                            "action": "debug",
                            "changed": false,
                            "msg": "This is play 1"
                        }
                    },
                    "task": {
                        "duration": {
                            "end": "2020-10-27T12:12:51.186216Z",
                            "start": "2020-10-27T12:12:51.179208Z"
                        },
                        "id": "58961d97-78ae-5e1e-8808-000000000008",
                        "name": "Play 1"
                    }
                }
            ]
        }
    ],
    "stats": {
        "localhost": {
            "changed": 0,
            "failures": 0,
            "ignored": 0,
            "ok": 1,
            "rescued": 0,
            "skipped": 0,
            "unreachable": 0
        }
    }
}
{
    "custom_stats": {},
    "global_custom_stats": {},
    "plays": [
        {
            "play": {
                "duration": {
                    "end": "2020-10-27T12:12:51.186216Z",
                    "start": "2020-10-27T12:12:51.172245Z"
                },
                "id": "58961d97-78ae-5e1e-8808-000000000006",
                "name": "all"
            },
            "tasks": [
                {
                    "hosts": {
                        "localhost": {
                            "_ansible_no_log": false,
                            "_ansible_verbose_always": true,
                            "action": "debug",
                            "changed": false,
                            "msg": "This is play 1"
                        }
                    },
                    "task": {
                        "duration": {
                            "end": "2020-10-27T12:12:51.186216Z",
                            "start": "2020-10-27T12:12:51.179208Z"
                        },
                        "id": "58961d97-78ae-5e1e-8808-000000000008",
                        "name": "Play 1"
                    }
                }
            ]
        },
        {
            "play": {
                "duration": {
                    "end": "2020-10-27T12:12:51.199701Z",
                    "start": "2020-10-27T12:12:51.189341Z"
                },
                "id": "58961d97-78ae-5e1e-8808-00000000001a",
                "name": "all"
            },
            "tasks": [
                {
                    "hosts": {
                        "localhost": {
                            "_ansible_no_log": false,
                            "_ansible_verbose_always": true,
                            "action": "debug",
                            "changed": false,
                            "msg": "This is play 2"
                        }
                    },
                    "task": {
                        "duration": {
                            "end": "2020-10-27T12:12:51.199701Z",
                            "start": "2020-10-27T12:12:51.191727Z"
                        },
                        "id": "58961d97-78ae-5e1e-8808-00000000001c",
                        "name": "Play 2"
                    }
                }
            ]
        }
    ],
    "stats": {
        "localhost": {
            "changed": 0,
            "failures": 0,
            "ignored": 0,
            "ok": 2,
            "rescued": 0,
            "skipped": 0,
            "unreachable": 0
        }
    }
}
```

**Comment by saito-hideki** [comment] 2021-04-21 00:14
@lucas-benedito
In this case, I think you can use `json_verify -s` like below:

```
$ ANSIBLE_STDOUT_CALLBACK=json ansible-playbook -i localhost, play1.yml play2.yml | json_verify -s
JSON is valid
```

I hope this helps.

**Comment by Akasurde** [comment] 2021-06-16 10:12
@lucas-benedito When running multiple playbooks at the same command returns multiple JSON stream. Like @saito-hideki said, you need to use `json_verify -s` to handle that JSON stream.

needs_info

**Comment by lucas-benedito** [comment] 2021-06-17 14:04
@Akasurde if this is intended and should not be changed, we may close this issue.

**Comment by Akasurde** [comment] 2021-06-17 14:09
@lucas-benedito yes, this is working as intended. I will close this. Please feel free to open a new issue if the problem persists. Thanks

**Closed by Akasurde** 2021-06-17 14:09 UTC
Labels: needs_info, question, verified
