### ISSUE TITLE
authorized_key removing entries without instruction

### ISSUE THREAD

**Issue by phemmer** [ansible-collections/ansible.posix#457] opened 2023-05-09 23:40 UTC
##### SUMMARY

The authorized_key module is deleting entries from the authorized_keys file without being told to do so.

This seems to be happening when there are multiple entries with the same key.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

authorized_key

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.5]
  config file = None
  configured module search path = ['/home/phemmer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/phemmer/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/phemmer/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/phemmer/.local/bin/ansible
  python version = 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection    Version
------------- -------
ansible.posix 1.5.2  
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT

Debian & Fedora

##### STEPS TO REPRODUCE

```
# cat > /tmp/keys <<EOF
from="1.2.3.4" ssh-rsa a foo
from="5.6.7.8" ssh-rsa a bar
EOF

# ansible localhost -m authorized_key -a "user=nobody manage_dir=false path=/tmp/keys key=\"ssh-rsa abcd foo\""
```

*Also as a side note, I don't understand why the `user` field is required. As you can see in the above, I just filled it in with a garbage user*

##### EXPECTED RESULTS

```
# cat /tmp/keys
from="1.2.3.4" ssh-rsa a foo
from="5.6.7.8" ssh-rsa a bar
ssh-rsa abcd foo
```

##### ACTUAL RESULTS

```
# cat /tmp/keys                                                                                              
from="5.6.7.8" ssh-rsa a bar
ssh-rsa abcd foo
```

**Comment by robolmos** [comment] 2023-05-19 20:58
Looks like it's because the module treats the key as the unique index for the list of parsed keys: https://github.com/ansible-collections/ansible.posix/blob/f48515aad3f253fd7f8a2830b42b0bd0fa6cd727/plugins/modules/authorized_key.py#L485-L486

**Comment by bcoca** [comment] 2024-07-12 17:01
This is 'by design' as you are stating 'this is the list of keys that should be in the file', anything outside that list is removed.

To change this behavior  look at the `exclusive` option. https://github.com/ansible-collections/ansible.posix/blob/main/plugins/modules/authorized_key.py#L56

**Comment by Akasurde** [comment] 2024-07-12 17:10
Closing as per the above comment.

**Closed by Akasurde** 2024-07-12 17:10 UTC

**Comment by phemmer** [comment] 2024-07-12 17:11
> This is 'by design' as you are stating 'this is the list of keys that should be in the file', anything outside that list is removed.
> 
> To change this behavior look at the `exclusive` option. https://github.com/ansible-collections/ansible.posix/blob/main/plugins/modules/authorized_key.py#L56

I think you misread the description. It also does not behave as you describe (that option does not work as documented). 

```
# cat keys
from="1.2.3.4" ssh-rsa a foo
from="5.6.7.8" ssh-rsa a bar
from="9.10.11.12" ssh-rsa b baz

# ansible localhost -m authorized_key -a "user=nobody manage_dir=false path=/tmp/keys key=\"ssh-rsa abcd foo\""

# cat keys
from="5.6.7.8" ssh-rsa a bar
from="9.10.11.12" ssh-rsa b baz
ssh-rsa abcd foo
```

If it behaved as described, all keys other than the `abcd foo` would be removed. They are not. The only one that was removed was the duplicate.

**Comment by phemmer** [comment] 2024-07-12 17:12
Please reopen per above comment.

**Comment by bcoca** [comment] 2024-07-12 17:15
The description did mention duplicate keys, but that was not the only case stated. I answered the more generic question. But yes, duplicates are removed in all cases, by design and there is no option to avoid this.

If `exclusive` does not work as documented, that is a bug, but not the same as what this issue reported.
