### ISSUE TITLE
Using posix.mount in AAP 2.1 throws: Unable to apply new capability set

### ISSUE THREAD

**Issue by fhamed** [ansible-collections/ansible.posix#310] opened 2022-01-13 15:39 UTC
##### SUMMARY

Using the module mount in Ansible Platform 2.1, which runs playbooks within containers, throws the following error:
"Unable to apply new capability set."

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

posix.mount

##### ANSIBLE VERSION

```paste below

VERSIONS (via ansible-navigator):

ansible:
collections:
  details:
    ansible.posix: 1.2.0
    ansible.utils: 2.4.2
    community.general: 4.2.0
	...
version:
  details: core 2.12.1

OS:
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"

podman version 3.3.1
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

- name: Mount task
  become: true
  ansible.posix.mount:
    path: /tmp/test
    src: 10.xx.xx.14/pac
    fstype: cifs
    opts: "rw,vers=3.0,dir_mode=0777,file_mode=0777,serverino,username=myuser,password=mypass"
    state: mounted
  delegate_to: localhost

```

##### ACTUAL RESULTS

```paste below

```

**Comment by saito-hideki** [comment] 2022-01-20 05:39
@fhamed thank you for reporting this.
Sorry if I misunderstood your situation, but this problem appears to be caused by a configuration on the container engine side. Therefore, please review your docker or podman settings. You can see a similar issue on mody engine like below:

- REF: https://github.com/moby/moby/issues/22197

**Comment by fhamed** [comment] 2022-01-20 08:46
@saito-hideki Thanks for your response and for the link. I did the following:

$ podman run -it --rm  --cap-add SYS_ADMIN --cap-add DAC_READ_SEARCH …

bash-4.4#   mount -t cifs //<ip>/test /mnt/test -o vers=3.0,credentials=/etc/smbcredentials/my.cred,dir_mode=0777,file_mode=0777,serverino
mount error(1): Operation not permitted
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)

bash-4.4# dmesg
dmesg: read kernel buffer failed: Permission denied

bash-4.4# ls -alrt /mnt/
total 0
drwxr-xr-x.  2 root root   26 Jan 20 08:45 test

bash-4.4# id
uid=0(root) gid=0(root) groups=0(root)

**Comment by saito-hideki** [comment] 2022-01-20 09:07
@fhamed It seems to be a problem with the container engine configuration. Therefore, I don't think this is a problem specific to the ansible.posix.mount module. :)

**Comment by fhamed** [comment] 2022-01-20 11:03
@saito-hideki Yes, it seems so. Even if I get it resolved on the command line another problem is that I use the ansible automation controller (aka tower), which runs jobs within execution environments (container) and it does not provide any possibility to pass parameters (like --cap-add SYS_ADMIN) for the job templates. I will check this with red hat support. Thanks again for your help.

**Comment by saito-hideki** [comment] 2022-01-20 12:47
@fhamed no problem at all.
So I will close this issue :)

**Closed by saito-hideki** 2022-01-20 12:47 UTC
Labels: needs_info, needs_verified

**Comment by alvarofernandezavalos** [comment] 2024-10-11 10:53
> @saito-hideki Yes, it seems so. Even if I get it resolved on the command line another problem is that I use the ansible automation controller (aka tower), which runs jobs within execution environments (container) and it does not provide any possibility to pass parameters (like --cap-add SYS_ADMIN) for the job templates. I will check this with red hat support. Thanks again for your help.

I have the same problem now, How can I mount a cifs inside execution environment?

**Comment by saito-hideki** [comment] 2024-10-16 00:04
@alvarofernandezavalos  Thanks for the comment :)
Sorry if I missed the background, but If you are running into the same problem with the execution environment, it seems like a problem that should be addressed on the execution environment side.
